services:
  snell:
    image: snell-v6:official
    container_name: snell
    restart: always
    network_mode: host
    volumes:
      - ./snell-config:/etc/snell
    command: ["-c", "/etc/snell/snell-server.conf"]
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"